name: "Commit"
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 6 * * 1"
permissions:
  contents: "write"
defaults:
  run:
    shell: "bash"
concurrency:
  group: "update-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  update:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - uses: "actions/checkout@v3"
      - run: "git config -l"
      - run: |
          export GIT_AUTHOR_NAME="$(gh api users/${GITHUB_SENDER_LOGIN} --jq '.name')"
          date > generated.txt
          git add .
          git commit -m "generated"
          git push
        env:
          GITHUB_SENDER_LOGIN: "${{ github.event.sender.login }}"
          GIT_AUTHOR_EMAIL: "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      - run: "git config -l"
