name: "Update CC-CEDICT"
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "4/15 * * * *"
permissions:
  contents: "write"
defaults:
  run:
    shell: "bash"
concurrency:
  group: "update-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  update:
    name: "Update CC-CEDICT"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v3"
      - name: "Configure Git"
        run: |
          git config user.name "Rodolfo Carvalho"
          git config user.email "88819+rhcarvalho@users.noreply.github.com"
      - name: "Download"
        run: |
          URL='https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz'
          curl -L ${URL} | gunzip > cedict_1_0_ts_utf-8_mdbg.txt
      - name: "Check for changes"
        id: "diff"
        run: |
          git add -- cedict_1_0_ts_utf-8_mdbg.txt
          git diff --cached | head -100
          echo "::set-output name=changed::$(git diff --cached --quiet; echo $?)"
      - name: "Commit"
        if: "steps.diff.outputs.changed"
        run: |
          RELEASE_DATE="$(awk 'match($0, "^^#! date=(.+)$", m) {print m[1];exit}' cedict_1_0_ts_utf-8_mdbg.txt)"
          git commit -m "CC-CEDICT ${RELEASE_DATE}"
      - name: Push
        if: "steps.diff.outputs.changed"
        run: |
          git push
